wandb_version: 1

batch_size:
  desc: null
  value: 128
dropout_rate:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.002255886604227257
lstm_units:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.8
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714708764.853869
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 105
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 105
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.10.9
      5: 0.15.8
      8:
      - 4
      - 5
      10:
      - 9
